image:
  registry: docker.io
  repository: ywucontainer/hiresify
  tag: client.latest
  pullPolicy: Always
  debug: false

imagePullSecrets:
  - name: docker-config

ingress:
  enabled: false

resources:
  requests:
    cpu: 0.1
    memory: 64Mi
  limits:
    cpu: 0.2
    memory: 128Mi

service:
  type: NodePort
  port: 3000
  nodePort: 30030

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40

podLabels: {}

nodeSelector: {}

tolerations: []

affinity: {}
