apiVersion: v1
kind: Namespace
metadata:
  name: hiresify
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: hiresify
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {docker_config}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: hiresify
type: Opaque
data:
  minio-username: dXNlcg==
  minio-password: MTIzNDU2Nzg=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: hiresify
type: Opaque
data:
  postgresql-password: MTIzNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: hiresify
type: Opaque
data:
  redis-password: MTIzNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: hiresify-config
  namespace: hiresify
type: Opaque
stringData:
  hiresify-config: |-
    access_ttl=900
    blob_access_key=user
    blob_secret_key=12345678
    blob_store_region=us-east-1
    blob_store_url=http://minio:9000
    blob_ttl=30
    cache_ttl=300
    database_config={{"pool_size": 5, "max_overflow": 5, "pool_pre_ping": true}}
    database_url=postgresql+asyncpg://user:1234@postgres:5432/hiresify
    redis_url=redis://:1234@redis:6379/0
    refresh_ttl=30
    upload_ttl=7
