apiVersion: v1
kind: Namespace
metadata:
  name: hiresify
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: hiresify
type: Opaque
data:
  redis-password: {redis_password}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: hiresify
type: Opaque
data:
  postgres-password: {postgres_password}
