# Copyright (c) 2025 Yifeng Wu
# All rights reserved.
# This file is not licensed for use, modification, or distribution without
# explicit written permission from the copyright holder.

"""Define the domain model for upload management."""

from datetime import UTC, datetime

from pydantic.dataclasses import dataclass

from hiresify_engine.util import check_tz


@dataclass(frozen=True)
class Upload:
    """Wrap user-facing fields and methods for an upload."""

    #: The UID of this upload generated by the blob service.
    uid: str

    #: The blob key to identify the blob in the blob store.
    blob_key: str

    #: The date and time when the upload was created.
    created_at: datetime

    #: The date and time when the upload is valid through.
    valid_thru: datetime

    def __post_init__(self) -> None:
        """Perform post init checks."""
        check_tz(self.created_at)
        check_tz(self.valid_thru)

    def is_valid(self) -> bool:
        """Check if this upload is still valid or expired."""
        return self.valid_thru > datetime.now(UTC)
