services:
  minio:
    command: server /data --console-address :9001
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_REGION_NAME: us-east-1
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 5s
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      timeout: 3s
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
    volumes:
      - iodata:/data

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: hiresify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 5s
      test: ["CMD", "psql", "-U", "user", "-d", "hiresify", "-c", "SELECT 1"]
      timeout: 3s
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 5s
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  fastapi:
    command: >
      uv run uvicorn hiresify_engine.app.main:app
      --access-log
      --host 0.0.0.0
      --log-level debug
      --port 8000
      --workers 1
    container_name: fastapi
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      CONFIG_DIR: /etc/hiresify
      DEPLOYMENT: development
    image: hiresify:${TAG}
    ports:
      - 8000:8000
    volumes:
      - .env.development:/etc/hiresify/.env.development:ro

volumes:
  iodata:
  pgdata:
