services:
  minio:
    command: server /data --console-address :9001
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_REGION_NAME: us-east-1
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
    volumes:
      - iodata:/data

volumes:
  iodata:
