services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: hiresify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 10s
      test: ["CMD", "psql", "-U", "user", "-d", "hiresify", "-c", "SELECT 1"]
      timeout: 3s
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    healthcheck:
      interval: 5s
      retries: 5
      start_period: 5s
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  fastapi:
    command: >
      uv run uvicorn hiresify_engine.app.main:app
      --access-log
      --host 0.0.0.0
      --log-level debug
      --port 8000
      --workers 2
    container_name: fastapi
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://user:1234@postgres:5432/hiresify
      REDIS_URL: redis://redis:6379
    image: hiresify:${TAG}
    ports:
      - 8000:8000

volumes:
  pgdata:
