services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: hiresify
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  fastapi:
    command: >
      uv run uvicorn hiresify_engine.app.main:app
      --host 0.0.0.0
      --port 8000
    container_name: fastapi
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://user:1234@postgres:5432/hiresify
      REDIS_URL: redis://redis:6379
    image: hiresify:${TAG}
    ports:
      - 8000:8000

volumes:
  pgdata:
